// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzPIoVupEaopS7iOZzDzJF3Vv9ZIoOA3M',
    appId: '1:60634345877:web:30e83f50802d37f56c469c',
    messagingSenderId: '60634345877',
    projectId: 'ebookstore-76c0c',
    authDomain: 'ebookstore-76c0c.firebaseapp.com',
    storageBucket: 'ebookstore-76c0c.appspot.com',
    measurementId: 'G-95LXH43X97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB-r_O4SyB_UHMu2MXCILiYjEnVRCVLqo',
    appId: '1:60634345877:android:a00e110eb937be566c469c',
    messagingSenderId: '60634345877',
    projectId: 'ebookstore-76c0c',
    storageBucket: 'ebookstore-76c0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhQsN403D2HL59Y6radN5TCk9aL0fY06E',
    appId: '1:60634345877:ios:cc88f8341352ed426c469c',
    messagingSenderId: '60634345877',
    projectId: 'ebookstore-76c0c',
    storageBucket: 'ebookstore-76c0c.appspot.com',
    iosBundleId: 'com.example.bookstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhQsN403D2HL59Y6radN5TCk9aL0fY06E',
    appId: '1:60634345877:ios:95a6145834c7770e6c469c',
    messagingSenderId: '60634345877',
    projectId: 'ebookstore-76c0c',
    storageBucket: 'ebookstore-76c0c.appspot.com',
    iosBundleId: 'com.example.bookstore.RunnerTests',
  );
}
